version: "3.1"
services:
  chare:
      image: servostar/chare:latest
      restart: unless-stopped
      ports:
        - "8080:80"
      volumes:
        - ./public:/var/share
        - ./repos.tsv:/srv/config/repos.tsv
        - ./.ignore:/srv/config/.ignore
      environment:
        # should be setup if running behind reverse proxy
        - OVERWRITE_URL = https://cdn.example.com
        # these are all optional
        - OVERWRITE_SERVER_NAME = cdn.example.com
        - HOME_PAGE = https://home.example.com
        - LEGAL_PAGE = https://home.example.com
        - IMPRESSUM_PAGE = https://legal.example.com